<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2010-05-21 11:27

$extensionPath = t3lib_extMgm::extPath('seminarscalredirect');
return array(
	'tx_seminarscalredirect_pi1' => $extensionPath . 'pi1/class.tx_seminarscalredirect_pi1.php',
);
?>